train_split: train split
eval_split: 4k samples of eval_split

# Full list of trainer arguments
Trainer Arguments:
  output_dir: ./Gemma3ToxicTextClassifier
  overwrite_output_dir: None
  do_train: False
  do_eval: True
  do_predict: False
  eval_strategy: epoch
  prediction_loss_only: False
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 4
  per_gpu_train_batch_size: None
  per_gpu_eval_batch_size: None
  gradient_accumulation_steps: 1
  eval_accumulation_steps: 2
  eval_delay: 0
  torch_empty_cache_steps: 250
  learning_rate: 3e-05
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  num_train_epochs: 5
  max_steps: -1
  lr_scheduler_type: constant
  lr_scheduler_kwargs: {}
  warmup_ratio: 0.1
  warmup_steps: 0
  log_level: passive
  log_level_replica: warning
  log_on_each_node: True
  logging_dir: ./Gemma3ToxicTextClassifier/runs/Oct20_15-59-14_cs-01k812dpyd3513n7adz97be8mp
  logging_strategy: steps
  logging_first_step: False
  logging_steps: 500
  logging_nan_inf_filter: False
  save_strategy: epoch
  save_steps: 500
  save_total_limit: 2
  save_safetensors: True
  save_on_each_node: False
  save_only_model: False
  restore_callback_states_from_checkpoint: False
  no_cuda: False
  use_cpu: False
  use_mps_device: False
  seed: 3407
  data_seed: 3407
  jit_mode_eval: False
  use_ipex: False
  bf16: True
  fp16: False
  fp16_opt_level: O1
  half_precision_backend: auto
  bf16_full_eval: True
  fp16_full_eval: False
  tf32: None
  local_rank: 0
  ddp_backend: None
  tpu_num_cores: None
  tpu_metrics_debug: False
  debug: []
  dataloader_drop_last: False
  eval_steps: None
  dataloader_num_workers: 0
  dataloader_prefetch_factor: None
  past_index: -1
  run_name: None
  disable_tqdm: False
  remove_unused_columns: True
  label_names: None
  load_best_model_at_end: False
  metric_for_best_model: None
  greater_is_better: None
  ignore_data_skip: False
  fsdp: []
  fsdp_min_num_params: 0
  fsdp_config: {'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False}
  fsdp_transformer_layer_cls_to_wrap: None
  accelerator_config: {'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None}
  parallelism_config: None
  deepspeed: None
  label_smoothing_factor: 0.0
  optim: adamw_torch_fused
  optim_args: None
  adafactor: False
  group_by_length: False
  length_column_name: length
  report_to: []
  ddp_find_unused_parameters: None
  ddp_bucket_cap_mb: None
  ddp_broadcast_buffers: None
  dataloader_pin_memory: True
  dataloader_persistent_workers: False
  skip_memory_metrics: True
  use_legacy_prediction_loop: False
  push_to_hub: False
  resume_from_checkpoint: None
  hub_model_id: None
  hub_strategy: every_save
  hub_token: <HUB_TOKEN>
  hub_private_repo: None
  hub_always_push: False
  hub_revision: None
  gradient_checkpointing: False
  gradient_checkpointing_kwargs: None
  include_inputs_for_metrics: False
  include_for_metrics: []
  eval_do_concat_batches: True
  fp16_backend: auto
  push_to_hub_model_id: None
  push_to_hub_organization: None
  push_to_hub_token: <PUSH_TO_HUB_TOKEN>
  mp_parameters: 
  auto_find_batch_size: False
  full_determinism: False
  torchdynamo: None
  ray_scope: last
  ddp_timeout: 1800
  torch_compile: False
  torch_compile_backend: None
  torch_compile_mode: None
  include_tokens_per_second: False
  include_num_input_tokens_seen: False
  neftune_noise_alpha: None
  optim_target_modules: None
  batch_eval_metrics: False
  eval_on_start: False
  use_liger_kernel: False
  liger_kernel_config: None
  eval_use_gather_object: False
  average_tokens_across_devices: False
  model_init_kwargs: None
  chat_template_path: None
  dataset_text_field: text
  dataset_kwargs: {'add_special_tokens': False, 'append_concat_token': True}
  dataset_num_proc: 12
  eos_token: <EOS_TOKEN>
  pad_token: <PAD_TOKEN>
  max_length: 256
  packing: False
  packing_strategy: bfd
  padding_free: False
  pad_to_multiple_of: 128
  eval_packing: None
  completion_only_loss: None
  assistant_only_loss: False
  loss_type: nll
  activation_offloading: False
  vllm_sampling_params: None
  unsloth_num_chunks: -1
  max_seq_length: 256